#!/usr/bin/env sh
set -e

alias activate="gdbus call --session \
--dest org.gnome.Shell \
--object-path /gs/le0/zen/WindowFocus \
--method gs.le0.zen.WindowFocus.focusByWmClassOnWorkspace"

ec_gnome () {
    if systemctl --user is-active org.gnome.Shell@wayland.service --quiet; then
        export WAYLAND_DISPLAY=wayland-0
        export GDK_BACKEND=wayland
    fi

    if [ "$(activate 'Emacs')" == "(true,)" ]; then
        emacsclient --no-wait "${@}"
    else
        emacsclient --no-wait --create-frame "${@}"
    fi
}

ec_xorg () {
    id="$(xdo id -d -N Emacs)"
    if ! [ -z "$id" ]; then
        xdo activate -r "$id"
        if ! [ -z "$@" ]; then
            emacsclient --no-wait "${@}"
        fi
    else
        emacsclient --no-wait --create-frame "${@}"
    fi
}

if systemctl --user is-active org.gnome.Shell.target --quiet; then
    ec_gnome "${@}"
elif command -v xdo >/dev/null; then
    ec_xorg "${@}"
else
    emacsclient --no-wait --create-frame "${@}"
fi
