#!/usr/bin/env sh
file="${1:-README.md}"
target="${file}.html"
echo "" > $target

html() {
    echo "$@" >> $target
}

# Generate header
html '<head>'
html '<link rel=stylesheet type=text/css href=https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.1.0/github-markdown.min.css>'
html '<style>
.markdown-body {
  box-sizing: border-box;
  min-width: 200px;
  max-width: 980px;
  margin: 0 auto;
  padding: 45px;
}
@media (max-width: 767px) {
  .markdown-body {
    padding: 15px;
  }
}
</style>'
html '</head>'

# Generate body
html '<body class="markdown-body">'
gh api -X POST /markdown -F text=@"$file" >> $target
html '</body>'
